import type { AppConfig } from "../config";
import type { BuiltCommand } from "./buildBaselineCommand";

export function buildAbrCommand(config: AppConfig): BuiltCommand {
  const manifestPath = `${config.paths.dashRoot}/live-abr.mpd`;
  const windowSize = Math.max(
    1,
    Math.floor(
      config.streaming.dvrWindowSeconds /
        config.streaming.segmentDurationSeconds,
    ),
  );

  return {
    command: "ffmpeg",
    manifestPath,
    args: [
      "-hide_banner",
      "-y",
      "-framerate",
      String(config.capture.frameRate),
      "-use_wallclock_as_timestamps",
      "1",
      "-f",
      config.capture.inputFormat,
      "-pixel_format",
      config.capture.pixelFormat,
      "-video_size",
      config.capture.videoSize,
      "-i",
      config.capture.inputSource,
      "-an",
      "-filter_complex",
      "[0:v]split=3[v1][v2][v3];[v1]scale=640:360[v1out];[v2]scale=960:540[v2out];[v3]scale=1280:720[v3out]",
      "-map",
      "[v1out]",
      "-c:v:0",
      "libx264",
      "-b:v:0",
      "400k",
      "-preset",
      "veryfast",
      "-tune",
      "zerolatency",
      "-g",
      "30",
      "-keyint_min",
      "30",
      "-sc_threshold",
      "0",
      "-pix_fmt",
      "yuv420p",
      "-map",
      "[v2out]",
      "-c:v:1",
      "libx264",
      "-b:v:1",
      "1000k",
      "-preset",
      "veryfast",
      "-tune",
      "zerolatency",
      "-g",
      "30",
      "-keyint_min",
      "30",
      "-sc_threshold",
      "0",
      "-pix_fmt",
      "yuv420p",
      "-map",
      "[v3out]",
      "-c:v:2",
      "libx264",
      "-b:v:2",
      "2500k",
      "-preset",
      "veryfast",
      "-tune",
      "zerolatency",
      "-g",
      "30",
      "-keyint_min",
      "30",
      "-sc_threshold",
      "0",
      "-pix_fmt",
      "yuv420p",
      "-f",
      "dash",
      "-seg_duration",
      String(config.streaming.segmentDurationSeconds),
      "-window_size",
      String(windowSize),
      "-extra_window_size",
      "0",
      "-remove_at_exit",
      "0",
      "-adaptation_sets",
      "id=0,streams=v",
      manifestPath,
    ],
  };
}
